#pragma once

#define UPDATE_CREATE_DATABASE	0x01
#define UPDATE_DROP_DATABASE	0x02
#define UPDATE_OPEN_DATABASE	0x03

#define UPDATE_CREATE_TABLE		0x04
#define UPDATE_DROP_TABLE		0x05
#define UPDATE_ALTER_TABLE		0x06

#define MENU_DATABASE			1
#define MENU_TABLE				2
#define MENU_FIELD				3
#define MENU_RECORD				4
#define MENU_RCLICK				-1